language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements/dev.txt
  - pip install coveralls

before_script:
  - cp zurnatikl/localsettings.py.dist zurnatikl/localsettings.py
  - echo "SECRET_KEY = '`python -c 'import uuid; print uuid.uuid4()'`'" >> zurnatikl/localsettings.py

script:
  - python manage.py test

after_success:
  - coveralls
